services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: soulsync-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=soulsync
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Бэкенд на FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soulsync-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/soulsync
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - UPLOAD_DIR=/app/uploads
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://frontend:3000
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: >
      bash -c "alembic upgrade head && 
               uvicorn app.main:app --host 0.0.0.0 --port 8000"

  # Фронтенд на Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: soulsync-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  postgres_data: 